site_name: 'BIPES'
nav:
  - CoderDojo Mentor Resources: https://coderdojotc.github.io/bipes/
  - BIPES Home: index.md
  - Introduction:
    - About BIPES: intro/01-intro.md
    - Getting Started: intro/02-getting-started.md
  - Raspberry Pi Pico:
    - Basic Examples:
      - Introduction: pico/basics/01-intro.md
      - Blink: pico/basics/blink.md
      - Lab 3: pico/basics/03-lab.md
    - Sensors:
      - Introduction: pico/sensors/01-intro.md
    - Motors and Servos:
      - Introduction: pico/motors/01-intro.md
  - Glossary: glossary.md
  - References: references.md
  - Contributing: contributing.md
  - Contacts: contacts.md

site_description: 'Resources for teaching BIPES to CoderDojo Twin Cities students.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary and Jim Tannenbaum'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/CoderDojoTC/bipes'

# CoderDojo Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
